/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameDefini.java
 *
 * Created on May 22, 2012, 7:54:28 PM
 */
package biblioteca;

import dao.TrabajoXML;
import dominio.DifinicionAutor;
import dominio.Termino;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Eduardo
 */
public class FrameDefini extends javax.swing.JFrame {

    /** Creates new form FrameDefini */
    public FrameDefini() {
        initComponents();
        actualizatAutores();
        actualizatArchivos();
    }
    
    private Termino termi;

    private void actualizatAutores() {
        TrabajoXML xml = new TrabajoXML();
        jComboBox1.removeAllItems();
        List<String> lis = new ArrayList<String>();
        try {
            lis = xml.obtenerAutores();
        } catch (Exception ex) {
            Logger.getLogger(BibliotecaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < lis.size(); i++) {
            jComboBox1.addItem(lis.get(i));
        }
        jComboBox1.setSelectedIndex(-1);
    }
    
    private void actualizatArchivos() {
        TrabajoXML xml = new TrabajoXML();
        jComboBox2.removeAllItems();
        List<String> lis = new ArrayList<String>();
        try {
            lis = xml.obtenerArchivos();
        } catch (Exception ex) {
            Logger.getLogger(BibliotecaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < lis.size(); i++) {
            jComboBox2.addItem(lis.get(i));
        }
        jComboBox2.setSelectedIndex(-1);
        jTextField3.setText("");
        jTextField4.setText("");
    }
    public void mostrarDefiniciones(){
            DefaultTableModel datosTabla = new DefaultTableModel();
        
            //selecciono el modelo de datos de la tabla para modificarlo
            datosTabla = (DefaultTableModel) jTable1.getModel();
            datosTabla.setRowCount(termi.getDefiniciones().size());
            
           
            
            //Paso la información a la tabla
            for(int i = 0; i < termi.getDefiniciones().size(); i++){
                datosTabla.setValueAt(termi.getDefiniciones().get(i).getDefinición(),i,0);
                datosTabla.setValueAt(termi.getDefiniciones().get(i).getAutor(),i,1);
                datosTabla.setValueAt(termi.getDefiniciones().get(i).getNombreArticulo() ,i,2);
                datosTabla.setValueAt(termi.getDefiniciones().get(i).getNombreArchivo(),i,3);
                datosTabla.setValueAt(termi.getDefiniciones().get(i).getPagDefinicion(),i,4);
                datosTabla.setValueAt(termi.getDefiniciones().get(i).getLocalizacionPC(),i,5);               
                datosTabla.setValueAt(termi.getDefiniciones().get(i).getDia()+"/"+termi.getDefiniciones().get(i).getMes()+"/"+termi.getDefiniciones().get(i).getAnno(),i,6);
            }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Definición", "Autor", "Nombre Documento", "Nombre Archivo", "Página", "Localización", "Fecha"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 400, 1170, 140);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(biblioteca.BibliotecaApp.class).getContext().getResourceMap(FrameDefini.class);
        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 40, 60, 14);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 20);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(100, 70, 470, 190);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 110, 20);

        jComboBox1.setEditable(true);
        jComboBox1.setName("jComboBox1"); // NOI18N
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(720, 70, 420, 20);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(670, 70, 80, 20);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(670, 110, 32, 14);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(720, 110, 420, 20);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(660, 170, 60, 14);

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(720, 200, 420, 20);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(650, 210, 70, 10);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(630, 250, 90, 10);

        jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(720, 240, 420, 20);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 330, 140, 20);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(550, 330, 130, 23);

        jComboBox2.setEditable(true);
        jComboBox2.setName("jComboBox2"); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(720, 160, 420, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 1190, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             Calendar c = Calendar.getInstance();
             c.setTime(new Date());
        
             String   dia = Integer.toString(c.get(Calendar.DATE));
             int mes = (c.get(Calendar.MONTH));
             String   annio = Integer.toString(c.get(Calendar.YEAR));
             mes++; 
        
        TrabajoXML xml = new TrabajoXML();
        DifinicionAutor nuevaDifi = new DifinicionAutor();
        nuevaDifi.setAnno(annio);
        nuevaDifi.setDia(dia);
        nuevaDifi.setMes(String.valueOf(mes));
        
        nuevaDifi.setDefinición(jTextArea1.getText());
        nuevaDifi.setAutor(jComboBox1.getSelectedItem().toString());
        nuevaDifi.setNombreArchivo(jComboBox2.getSelectedItem().toString());
        nuevaDifi.setNombreArticulo(jTextField4.getText());
        nuevaDifi.setLocalizacionPC(jTextField3.getText());
        nuevaDifi.setPagDefinicion(Integer.parseInt(jTextField1.getText()));
        
        this.termi.getDefiniciones().add(nuevaDifi);
        try {
            xml.annadirDifinicion(termi);
            mostrarDefiniciones();
        } catch (Exception ex) {
            Logger.getLogger(FrameDefini.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex() != -1){
        TrabajoXML xml = new TrabajoXML();
        try {
            jTextField4.setText(xml.obtenerNombreDocumento(jComboBox2.getSelectedItem().toString()));
            jTextField3.setText(xml.obtenerLocalizacionDocumento(jComboBox2.getSelectedItem().toString()));
            
        } catch (Exception ex) {
            Logger.getLogger(BibliotecaView.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrameDefini().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the termi
     */
    public Termino getTermi() {
        return termi;
    }

    /**
     * @param termi the termi to set
     */
    public void setTermi(Termino termi) {
        this.termi = termi;
    }
}
